name: Tests
on:
  pull_request:
    branches: [ main ]
  release:
    types: [published]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: test/run --docker
